import React from 'react';
import { products } from '../lib/products.js';
import { Footer, Header, ProductArt, ProductCard } from './ui.js';

const h = React.createElement;

export default function HomePage() {
  return h(React.Fragment, null,
    h(Header),
    h('main', null,
      h('section', { className: 'hero' },
        h('div', { className: 'hero-copy' },
          h('p', { className: 'edition-label' }, 'BỘ SƯU TẬP 08—26 / VIỆT NAM'),
          h('h1', null,
            'Bếp gọn.',
            h('span', null, 'Thanh toán gọn.'),
          ),
          h('p', { className: 'hero-lead' }, 'Đồ dùng vừa vặn cho gian bếp Việt. Chọn món, nhận VietQR đúng số tiền và biết ngay khi chuyển khoản hoàn tất.'),
          h('div', { className: 'hero-actions' },
            h('a', { className: 'button button-primary', href: '#san-pham' }, 'Chọn một món'),
            h('span', null, 'Xác nhận tự động bởi MONA Pay'),
          ),
        ),
        h('div', { className: 'hero-visual' },
          h(ProductArt, { tone: 'orange' }),
          h('div', { className: 'hero-note' },
            h('strong', null, '01'),
            h('span', null, 'Không nhập tay số tiền. Không chờ ảnh chụp giao dịch.'),
          ),
        ),
      ),
      h('section', { className: 'catalog', id: 'san-pham' },
        h('div', { className: 'section-heading' },
          h('p', { className: 'eyebrow' }, 'DANH MỤC NHỎ, DÙNG MỖI NGÀY'),
          h('h2', null, 'Ba món mở đầu.'),
          h('p', null, 'Mỗi món được đo lại theo mặt bếp, kệ và thói quen nấu ăn phổ biến ở nhà Việt.'),
        ),
        h('div', { className: 'product-list' },
          ...products.map((product, index) => h(ProductCard, { product, index, key: product.slug })),
        ),
      ),
      h('section', { className: 'buy-flow', id: 'cach-mua' },
        h('div', { className: 'flow-intro' },
          h('p', { className: 'eyebrow' }, 'TỪ GIỎ HÀNG ĐẾN ĐÃ TRẢ'),
          h('h2', null, 'Một vòng thanh toán ngắn đến mức kế toán cũng thích.'),
        ),
        h('ol', { className: 'flow-steps' },
          h('li', null, h('b', null, '01'), h('span', null, 'Chọn món'), h('p', null, 'Shop tạo đơn với số tiền chính xác.')),
          h('li', null, h('b', null, '02'), h('span', null, 'Quét VietQR'), h('p', null, 'MONA Pay tạo mã động gắn với đơn.')),
          h('li', null, h('b', null, '03'), h('span', null, 'Nhận hàng'), h('p', null, 'Webhook ký HMAC đổi đơn sang đã trả.')),
        ),
      ),
      h('aside', { className: 'stack-note' },
        h('span', null, 'HẠ TẦNG'), h('strong', null, 'VibeCloud'),
        h('span', null, 'THU TIỀN'), h('strong', null, 'MONA Pay'),
        h('span', null, 'DOMAIN / MAIL'), h('strong', null, 'Mona.Host'),
      ),
    ),
    h(Footer),
  );
}
